########## How To Use Docker Image ###############
##
##  Image Name: denny/pylint:1.0
##  Git link: https://github.com/DennyZhang/devops_docker_image/blob/tag_v5/codecheck/Dockerfile_pylint_1_0
##  Docker hub link:
##  Build docker image: docker build --no-cache -f Dockerfile_pylint_1_0 -t denny/pylint:1.0 --rm=true .
##  How to use: TODO
##      docker run -d -v . /code pylint denny/pylint:1.0 python /enforce_pylint.py --code_dir /code --check_ignore_file ci/.shellignore1
##      docker exec -it pylint python /enforce_pylint.py --code_dir . --check_ignore_file ci/.shellignore
##  Description: Enforce pylint check for python scripts
##################################################
# Base Docker image: https://hub.docker.com/r/muccg/pylint/

FROM codacy/codacy-pylint:1.0.121

LABEL maintainer "Denny<denny@dennyzhang.com>"

ADD https://raw.githubusercontent.com/DennyZhang/devops_public/tag_v5/python/enforce_pylint_check/enforce_pylint_check.py \
    /enforce_pylint_check.py

ENTRYPOINT ["/bin/bash"]
