########## How To Use Docker Image ###############
##
##  Image Name: denny/rubocopcheck:1.0
##  Git link: https://github.com/DennyZhang/devops_docker_image/blob/tag_v5/codecheck/Dockerfile_rubocopcheck_1_0
##  Docker hub link:
##  Build docker image: docker build --no-cache -f Dockerfile_rubocopcheck_1_0 -t denny/rubocopcheck:1.0 --rm=true .
##  How to use
##      docker run -t -d --privileged -v ${code_dir}:/code --name rubocopcheck --entrypoint=/bin/bash denny/rubocopcheck:1.0
##      docker exec -it rubocopcheck python /enforce_rubocopcheck.py --code_dir /code --check_ignore_file /.rubocopcheck_ignore
##  Description: Enforce rubocop check for ruby scripts
##################################################
# Base Docker image: https://hub.docker.com/r/koalaman/rubocopcheck/tags/

FROM quay.io/actcat/buildpack_ruby:latest

LABEL maintainer "Denny<denny@dennyzhang.com>"

user root

WORKDIR /

ADD https://raw.githubusercontent.com/DennyZhang/devops_public/tag_v6/python/enforce_rubocopcheck/enforce_rubocopcheck.py /enforce_rubocopcheck.py

RUN chmod o+x /*.py && \
    gem install rubocop rubocop-rspec && rubocop --version

ENTRYPOINT ["/bin/bash"]
