########## How To Use Docker Image ###############
##
##  Image Name: denny/jenkins:1.0
##  Git link: https://github.com/DennyZhang/devops_docker_image/blob/tag_v5/jenkins/Dockerfile_1_0
##  Docker hub link:
##  Build docker image: docker build --no-cache -f Dockerfile_1_0 -t denny/jenkins:1.0 --rm=true .
##  Description: Manage via Jenkins GUI
##################################################
# Base Docker image: https://hub.docker.com/_/jenkins/

FROM jenkins:2.46.2

LABEL maintainer "Denny<denny@dennyzhang.com>"

# Install thinbackup plugin
user root

# TODO: enable serverspec check

# Install jenkins plugins
RUN /usr/local/bin/install-plugins.sh structs && \
    /usr/local/bin/install-plugins.sh credentials && \
    /usr/local/bin/install-plugins.sh plain-credentials && \
    /usr/local/bin/install-plugins.sh display-url-api && \
    /usr/local/bin/install-plugins.sh workflow-step-api && \
    /usr/local/bin/install-plugins.sh junit && \
    /usr/local/bin/install-plugins.sh thinBackup && \
    /usr/local/bin/install-plugins.sh slack && \
    /usr/local/bin/install-plugins.sh timestamper && \
    /usr/local/bin/install-plugins.sh git

WORKDIR /var/jenkins_home
user jenkins
RUN mkdir /var/jenkins_home/tmp/
