########## How To Use Docker Image ###############
##
##  Image Name: denny/jenkins:1.0
##  Git link: https://github.com/DennyZhang/devops_docker_image/blob/tag_v5/jenkins/Dockerfile_1_0
##  Docker hub link:
##  Build docker image: docker build --no-cache -f Dockerfile_1_0 -t denny/jenkins:1.0 --rm=true .
##  Description: Manage via Jenkins GUI
##################################################
# Base Docker image: https://hub.docker.com/_/jenkins/

FROM jenkins:2.46.2

LABEL maintainer "Denny<denny@dennyzhang.com>"

# Install thinbackup plugin
user root

# Disable ssh host key check
ADD ssh_config /etc/ssh/ssh_config
# Serverspec Check
ADD run_serverspec.sh /usr/sbin/run_serverspec.sh
ADD gitconfig /var/jenkins_home/.gitconfig

# Install jenkins plugins
RUN /usr/local/bin/install-plugins.sh structs && \
    /usr/local/bin/install-plugins.sh credentials && \
    /usr/local/bin/install-plugins.sh plain-credentials && \
    /usr/local/bin/install-plugins.sh display-url-api && \
    /usr/local/bin/install-plugins.sh workflow-step-api && \
    /usr/local/bin/install-plugins.sh junit && \
    /usr/local/bin/install-plugins.sh thinBackup && \
    /usr/local/bin/install-plugins.sh slack && \
    /usr/local/bin/install-plugins.sh timestamper && \
    /usr/local/bin/install-plugins.sh git && \
    /usr/local/bin/install-plugins.sh dashboard-view && \

# Install serverspec
    apt-get -y update && apt-get install -y --no-install-recommends ruby rake && \
    echo "gem: --no-rdoc --no-ri" >> /etc/gemrc && \
    gem install serverspec && chmod 755 /usr/sbin/run_serverspec.sh && \

# Install python
    apt-get install -y --no-install-recommends python-pip && \
    pip install GitPython && \
    chown jenkins:jenkins /var/jenkins_home/.gitconfig
    # Install basic packages
    apt-get install -y --no-install-recommends vim

user jenkins

WORKDIR /var/jenkins_home

# Verify docker image
    ruby --version | grep "2.1.5" && gem --version | grep "2.2.2" && \
    rake --version | grep "10.3.2" && gem list serverspec | grep "2.38.1" && \
    which vim
